requires 'perl', '5.34';
requires 'Future::AsyncAwait', '0.70';
requires 'Mojo::Pg', '4.27';
requires 'Mojolicious', '9.39';
requires 'Mojo::Redis', '3.29';
requires 'UUID', '0.37';
requires 'Time::Piece';
requires 'MIME::Types';
requires 'Carp::Always';

requires 'Ref::Util';
requires 'Ref::Util::XS';

requires 'Role::Tiny';
requires 'Iterator::Simple';

requires 'Image::Magick';

on 'develop' => sub {
  requires 'DDP';
}

