name: Deploy

on:
  workflow_run:
    workflows: [Build Front, Build Back]
    types: [completed]
    branches:
      - master

jobs:
  deploy:
    name: Deploy Ansible Playbook
    needs:
      - build_push
    runs-on: ubuntu-latest
    environment: polyine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "doojonio/bloginya_config"
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: root
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook \
            -i inventory \
            --private-key private_key.pem \
            -u root \
            -e bloginya_google_client_id=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e bloginya_google_project_id=${{ secrets.GOOGLE_PROJECT_ID }} \
            -e bloginya_google_client_secret=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            p.deploy-polyine.yml
