name: Deploy backend using Ansible

on:
  push:
    branches:
      - master
    paths:
      - "back/**"

jobs:
  build_push:
    runs-on: ubuntu-latest
    environment: hpotato
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: cr.selcloud.ru
          password: ${{ secrets.CR_TOKEN }}
          username: token
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./back
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: cr.selcloud.ru/registry-12/bloginya_back:latest

  deploy:
    name: Deploy Ansible Playbook
    needs:
      - build_push
    runs-on: ubuntu-latest
    environment: hpotato
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: "doojonio/bloginya_config"
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: root
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook \
            -i inventory \
            --private-key private_key.pem \
            -u root \
            -e bloginya_google_client_id=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e bloginya_google_project_id=${{ secrets.GOOGLE_PROJECT_ID }} \
            -e bloginya_google_client_secret=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            p.deploy-app.yml
