name: Build Front Dev

on:
  push:
    branches:
      - develop
    paths:
      - "front/**"

jobs:
  build_push:
    runs-on: ubuntu-latest
    environment: hpotato
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: cr.selcloud.ru
          password: ${{ secrets.CR_TOKEN }}
          username: token
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./front
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: cr.selcloud.ru/registry-12/bloginya_front:develop
